# Use a tty for gpg
# Solves error: "gpg: signing failed: Inappropriate ioctl for device"
GPG_TTY=$(tty)
export GPG_TTY

# Set my default GPG key
export GPGKEY=7E35837B

# Bug fix workaround: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1640514
[ -f "/etc/profile.d/apps-bin-path.sh" ] && source /etc/profile.d/apps-bin-path.sh
